### ISSUE TITLE
Parsing recipient value without having a full email

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [DockYard/elixir-mail#103]
This is a **feature request**

I have an email address in the format `Foo Bar <foo@bar.com>`. Unfortunately, the email is not in raw format, however I'd like to parse the address for the "name" part and the "address" part.

Is there any chance you could make the function [parse_recipient_value](https://github.com/DockYard/elixir-mail/blob/dfbd785d38910d04e6378ddd26a8c3172ab72f96/lib/mail/parsers/rfc_2822.ex#L296) public? It seems it could be used of the context of parsing an email, while still being useful.

**Comment by bcardarella** [comment]
I'm :+1: on that function being made public. Do you want to PR? Just confirm there is a unit test please 😄

**Comment by Fire-Dragon-DoL** [comment]
@bcardarella I'd be happy to make a PR and I wouldn't dare to skip unit tests for something public facing! :wink:

**Comment by hubertlepicki** [comment]
Thanks <3 just what I needed too.

**Comment by bcardarella** [comment]
I'll try to get around the publishing before EOY

**Comment by bcardarella** [comment]
Closed by #104
