### ISSUE TITLE
Encoders needed

### ISSUE THREAD

**Issue by bcardarella** [DockYard/elixir-mail#12]
Elixir comes with a Base64 encoder, but to be compliant with the spec we need the following:

- [x] 7-bit #27 
- [x] quoted-printable #25 
- [x] 8-bit #28
- [x] binary #29

**Comment by rgreenjr** [comment]
I'll take a stab at the quoted-printable encoder this weekend.

**Comment by rgreenjr** [comment]
I'll implement some of the others encoders this weekend.

**Comment by bcardarella** [comment]
Excellent, thank you

**Comment by rgreenjr** [comment]
@bcardarella Binary encoding is defined to as an arbitrary sequence of bytes with no length restriction. The `encode` and `decode` functions therefore just need to return their inputs as-is. This functionality matches the `Identity` encoder already in place. I can knock this out quickly but wanted to double check you didn't already plan on using the `Identity` encoder for this purpose.

**Comment by bcardarella** [comment]
@rgreenjr ok, if that's the case then just replace the `identity` encoder with `binary`

**Comment by rgreenjr** [comment]
@bcardarella Okay, sounds good.
