### ISSUE TITLE
UTF-8 in subject

### ISSUE THREAD

**Issue by sam701** [DockYard/elixir-mail#129]
The library does not encode UTF-8 characters in the (subject) header. This test fails:
```elixir
  test "subject" do
    import Mail
    subject = "test üä test"
    txt = Mail.build()
      |> put_subject(subject)
      |> render()
    encoded_subject = "=?UTF-8?Q?" <> Mail.Encoders.QuotedPrintable.encode(subject) <> "?="

    assert String.contains?(txt, encoded_subject)
  end
```

**Comment by bcardarella** [comment]
@sam701 can you PR this test?

**Comment by sam701** [comment]
@bcardarella  do you mean only the test or also the fix?

**Comment by bcardarella** [comment]
@sam701 if you want to implement the fix by all means :) If you PR this test I can PR your branch with a fix in the near future.

**Comment by sam701** [comment]
As far as I understand from [rfc 2047](https://tools.ietf.org/html/rfc2047) every header value must be word-encoded if it contains any non US-ASCII characters. Also in multipart. But I'm not sure how to handle the choice what [encoding](https://tools.ietf.org/html/rfc2047#section-4) (`B` or `Q`) to use. Is this the user choice `Mail.build_multipart(encoding: :base64)` or the encoder decides what encoding to use. 🤔
