### ISSUE TITLE
Question about other email projects

### ISSUE THREAD

**Issue by rgreenjr** [DockYard/elixir-mail#13]
Hi Brian,

I'm interested in helping with elixir-mail, but wanted make sure we aren't unnecessarily duplicating work. I found a couple other mail projects that look similar:

-    [Bamboo](https://github.com/paulcsmith/bamboo)
-    [Mailer](https://github.com/antp/mailer)

**Comment by bcardarella** [comment]
Both of those projects are handling the *sending* of the mails. They seem to have simple mail composition logic. The goal of this library is to implement the rfc2822 spec. It doesn't handle the sending or receiving in any way.

Check out the multipart branch. I am hopefully pushing and merging it into master today. It has better rfc2822 support for composing and parsing

**Comment by rgreenjr** [comment]
Excellent, I was hoping the answer would be something like this. Thanks.
