### ISSUE TITLE
Bug: Parsing of obsolete date format with timezone UT

### ISSUE THREAD

**Issue by priojk** [DockYard/elixir-mail#140]
## Version
0.2.3

## Test Case
Mail with the following date:

Date: Tue, 12 May 2020 12:08:24 UT

## Expected Behavior
The date is a valid, obsolete version according to RFC2822, so it should parse.

## Actual Behavior
The following error occurs:

** (FunctionClauseError) no function clause matching in Mail.Parsers.RFC2822.erl_from_timestamp/1
    (mail 0.2.3) lib/mail/parsers/rfc_2822.ex:50: Mail.Parsers.RFC2822.erl_from_timestamp("12 May 2020 12:08:24 UT")
    (mail 0.2.3) lib/mail/parsers/rfc_2822.ex:200: Mail.Parsers.RFC2822.parse_headers/2
    (mail 0.2.3) lib/mail/parsers/rfc_2822.ex:21: Mail.Parsers.RFC2822.parse/1

## Possible fix:

The following function is already present:
```
  # This adds support for a now obsolete format
  # https://tools.ietf.org/html/rfc2822#section-4.3
  def erl_from_timestamp(
        <<date::binary-size(2), " ", month::binary-size(3), " ", year::binary-size(4), " ",
          hour::binary-size(2), ":", minute::binary-size(2), ":", second::binary-size(2), " ",
          timezone::binary-size(3), _rest::binary>>
      ) do
    erl_from_timestamp("#{date} #{month} #{year} #{hour}:#{minute}:#{second} (#{timezone})")
  end
```

However, it expects a timezone with exactly three letters, which is true for all timezones except UT for the "regular" timezones.

Regarding the value for obsolete timezones, specified via obs-zone in the RFC2822, also military timezones with one letter are described and the RFC states that other timezones with three to five letters had been used as well. Therefore, I propose to just skip any potential trailing letters and set the actual timezone to +00:00.

The following function might be placed right under the one mentioned above:

```
  # additional fix for obsolete, non-three-letter-timezones
  def erl_from_timestamp(
        <<date::binary-size(2), " ", month::binary-size(3), " ", year::binary-size(4), " ",
          hour::binary-size(2), ":", minute::binary-size(2), ":", second::binary-size(2), " ",
         _rest::binary>>
      ) do
    erl_from_timestamp("#{date} #{month} #{year} #{hour}:#{minute}:#{second} (+00:00)")
  end
```

**Comment by bcardarella** [comment]
Closed by #143
