### ISSUE TITLE
MatchError when parsing attachments with a content disposition that does not contain a filename.

### ISSUE THREAD

**Issue by LetThereBeDwight** [DockYard/elixir-mail#154]
## Version
0.2.3

## Test Case
``` 
  test "parses an attachment with a minimal content-disposition" do
    message =
      parse_email("""
      To: Test User <user@example.com>, Other User <other@example.com>
      CC: The Dude <dude@example.com>, Batman <batman@example.com>
      From: Me <me@example.com>
      Content-Type: multipart/mixed; boundary="foobar"
      Date: Fri, 1 Jan
       2016 00:00:00 +0000

      --foobar
      Content-Type: multipart/alternative; boundary="bazqux"

      --bazqux
      Content-Type: text/plain

      This is some text

      --bazqux
      Content-Type: text/html

      <h1>This is the HTML</h1>

      --bazqux--
      --foobar
      Content-Type: text/markdown
      Content-Disposition: attachment
      Content-Transfer-Encoding: base64

      SGVsbG8gd29ybGQh
      --foobar--
      """)

    _attachments = Mail.get_attachments(message)
  end
```

This test will fail, it is a trimmed down version of the test defined at test/mail/parsers/rfc_2822_test.exs:218 - the only functional difference is that line 244 `Content-Disposition: attachment; filename=README.md`, we remove the portion `;filename=README.md`. 

## Steps to reproduce
See above and run that test - not entirely sure what the spec says about this but I'm seeing instances in the wild of the disposition being minimally defined to just be "attachment"

## Expected Behavior
Should be able to get attachments from such messages in some fashion.

## Actual Behavior
Attempting to get attachments from such messages results in a MatchError, as the system properly picks out that an attachment is included, but then forces a content-disposition match in `get_attachments/1` in `lib/mail.ex`:

```
def get_attachments(%Mail.Message{} = message) do
    walk_parts([message], {:cont, []}, fn message, acc ->
      case Mail.Message.is_attachment?(message) do
        true ->
          ["attachment", {"filename", filename} | _] =
            Mail.Message.get_header(message, :content_disposition)

          {:cont, List.insert_at(acc, -1, {filename, message.body})}

        false ->
          {:cont, acc}
      end
    end)
    |> elem(1)
  end
```

**Comment by andrewtimberlake** [comment]
Thanks @LetThereBeDwight , I checked RFC2183 and the filename property is optional for an attachment.
I will prepare a fix.

**Comment by LetThereBeDwight** [comment]
@andrewtimberlake your fix did not capture when the content-dispostion comes in simply as a string "attachment", which I believe is also a valid specification here.

**Comment by andrewtimberlake** [comment]
Thanks @LetThereBeDwight, I have updated the test and fix.
