### ISSUE TITLE
Subject not properly encoded to printable character

### ISSUE THREAD

**Issue by rlopzc** [DockYard/elixir-mail#157]
## Version
0.3.1

## Test Case
Subject header:
```
Subject: =?UTF-8?Q?Read_the_latest_posts_-_"Hyperdrive:_ma?= =?UTF-8?Q?king_databases_feel_like_they=E2=80=99re_global"?=
```

## Expected Behavior
Subject parsed as:
```
"subject" => "Read the latest posts - \"Hyperdrive: making databases feel like they’re global\""
```

## Actual Behavior
Mail parses the subject as:
```
"subject" => "Read_the_latest_posts_-_\"Hyperdrive:_ma king_databases_feel_like_they’re_global\"",
```

**Comment by andrewtimberlake** [comment]
Why do you believe that “_” should be decoded as “ ”?
I don’t see that in the [spec](https://datatracker.ietf.org/doc/html/rfc2045#section-6.7)

**Comment by rlopzc** [comment]
🤔 mostly because gmail shows the subject with spaces instead of _. I'm going to check the spec, thank you.

**Comment by rlopzc** [comment]
Closing this one, I didn't have the time to look into the spec.
