### ISSUE TITLE
String header keys instead of atom keys for sub-types

### ISSUE THREAD

**Issue by bcardarella** [DockYard/elixir-mail#16]
Atoms are not GC'd, and inbound emails being parsed could cause a DOS attack on an elixir app by hammering with infinitely unique header keys.

However, the current data model using keyword lists for the header values. Keyword values map very nicely to header values and subtypes:

```
Content-Type: multipart/mixed; boundary="foobar"
```

maps well to:

```
%{content_type: ["multipart/mixed", boundary: "foobar"]}
```

However, using string keys:

```
headers = %{"Content-Type" => ["multipart/mixed", {"boundary", "foobar"}]}
```

It seems that the `boundary` subtype value cannot be fetched:

```
iex(4)> Keyword.fetch(headers["Content-Type"], "boundary")
** (FunctionClauseError) no function clause matching in Keyword.fetch/2
    (elixir) lib/keyword.ex:288: Keyword.fetch(["multipart/mixed", {"boundary", "foobar"}], "boundary")
iex(4)>
```

**Comment by andrewtimberlake** [comment]
When parsing full delivery emails the number of headers increases dramatically, especially with extensions and X-type headers.
I’d like to tackle this change.

**Comment by IceDragon200** [comment]
I don't know if this helps, but you can use erlang's :proplists which allows string keys:

```elixir
# keyword
Keyword.get(list, key)
# proplist equivalent
:proplists.get_value(key, list)

# keyword
Keyword.put(list, key, new_value)
# proplist equivalent
List.keystore(list, key, 0, {key, new_value})
:lists.keystore(key, 1, list, {key, new_value})
```

http://erlang.org/doc/man/proplists.html
http://erlang.org/doc/man/lists.html

You may want to wrap it up to have a cleaner interface:

```elixir
Mail.Proplist.keys(list) # :proplists.get_keys(list)
Mail.Proplist.put(list, key, value) # :lists.keystore(key, 1, list, {key, value})
Mail.Proplist.get(list, key) # :proplists.get_value(key, list)
Mail.Proplist.merge(a, b) # :lists.keymerge(1, a, b)
Mail.Proplist.delete(list, key) # :proplists.delete(key, list)
Mail.Proplist.drop(list, keys) # need to roll a Enum.reduce here
Mail.Proplist.take(list, keys) # need to roll a Enum.reduce here
```

If that's done then the headers and subtypes could be replaced.
You may want to have a massive disclaimer afterwards for those upgrading to the new format since it would be completely incompatible at that point.

**Comment by bcardarella** [comment]
Closed by: https://github.com/DockYard/elixir-mail/pull/69
