### ISSUE TITLE
Mail.get_html fails with inline charset specifications

### ISSUE THREAD

**Issue by LetThereBeDwight** [DockYard/elixir-mail#171]
## Version
~0.4.0~ 0.3.1

## Test Case
  ```
  test "get_html with singlepart and content-type with inline charset spec" do
    mail =
      Mail.put_html(Mail.build(), "<h1>Some HTML</h1>")
      |> Mail.Message.put_content_type("text/html; charset=UTF-8")

    assert Mail.get_html(mail) == mail
  end
  ```
  
## Steps to reproduce
Run the test

## Expected Behavior
That mail.get_html returns the message in the above case

## Actual Behavior
Nil because no match

**Comment by andrewtimberlake** [comment]
The correct code should be:
```elixir
message
|> Mail.Message.put_content_type(["text/html", {"charset", "UTF-8"}])
```

**Comment by LetThereBeDwight** [comment]
> ```elixir
> ["text/html", {"charset", "UTF-8"}]
> ```

That results in a different content-type spec for the Mail object - this is mimicking an RFC2822 email that comes in with a specification like this:


```
    To: user@example.com
    From: me@example.com
    Reply-To: otherme@example.com
    Subject: Test Email
    Content-Type: text/html; charset=UTF-8;

    <h1>SOME HTML</h1
```

The fact that it's coming via RFC2822 isn't actually relevant so I boiled it down to a totally possible and valid content-type.
