### ISSUE TITLE
parse the envelope as well

### ISSUE THREAD

**Issue by schaary** [DockYard/elixir-mail#36]
I try to use elixir-mail to parse incoming mails. But they always start with the From-address of the envelope:

```mail
From foo@example.com  Sat Mar 19 09:08:14 2016
Return-Path: <foo@example.com>
X-Original-To: bar@example.com
Delivered-To: bar@example.com
Received: by example.com (Postfix, from userid 1000)
	id F2B491A5F34; Sat, 19 Mar 2016 09:08:13 +0100 (CET)
To: bar@example.com
Subject: say it loud
Message-Id: <20160319080813.F2B491A5F34@example.com>
Date: Sat, 19 Mar 2016 09:08:13 +0100 (CET)
From: foo@example.com (foo)

hello world
```

Currently elixir-mail parses 'only' the inside the the mail, not the envelope. 

Do you plan to deal with this case as well? I would like to send you a pull request but first I would like to know whether you are interested?

**Comment by bcardarella** [comment]
Which email provider are you using? The address field `From` for example is not spec, it should be:

```
From: foo <foo@example.com>
```

RFC2822 does only references 2821 in terms of the "envelope" and I cannot find in 2821 anything that resembles this. Unless you can find something in the spec that says we should respect a line similar to the first I would prefer not to parse it. It would probably be best for you to strip it from the email prior to parsing as it doesn't include any information that isn't already in the structured header.

**Comment by andrewtimberlake** [comment]
@shaary, I think the first line of your example is from the Maildir storage format. 
As Brian said, it isn’t part of the official RFC2822 format (which begins in your example from line 2).
If you’re processing emails like that, with the latest code in master, you can split the mail into lines, drop the first line and then feed the lines into the parser.

**Comment by schaary** [comment]
@andrewtimberlake I am assume it is the mbox [1] format. This is what I get when I use postfix on a ubuntu and pipe what I get inside of a .forward file into a elixir- (or something else) script. 
I'm going to restart my project again next week. Then I will try your hint. Thank you. 

[1] http://qmail.org/man/man5/mbox.html
