### ISSUE TITLE
no function clause matching in Mail.put_attachment/2 -when Adding Attachment from data, fails on put_attachment guard

### ISSUE THREAD

**Issue by misaelpc** [DockYard/elixir-mail#40]
## Test Case

https://gist.github.com/misaelpc/40e58a98c30de2bd22678b9416675264
## Steps to reproduce

When memory attachment is added 

|> Mail.put_attachment({"README.md", file_data})

The guard for function:

```
def put_attachment(%Mail.Message{multipart: true} = message, path) when is_binary(path),
    do: Mail.Message.put_part(message, Mail.Message.build_attachment(path))
```

Fails because we are sending a tuple
## Expected Behavior

Another guard should be added:

```
def put_attachment(%Mail.Message{multipart: true} = message, path) when is_tuple(path),
    do: Mail.Message.put_part(message, Mail.Message.build_attachment(path))
```
## Actual Behavior

no function clause matching in Mail.put_attachment/2 raise when adding in memory attachment

**Comment by bcardarella** [comment]
API came about from our internal use, which we didn't require the file data at this point. So this is a missing API function IMO and should be added. Do you want to PR this?

**Comment by misaelpc** [comment]
Sure 👍

**Comment by bcardarella** [comment]
Closed by: https://github.com/DockYard/elixir-mail/pull/58
