### ISSUE TITLE
An empty header field causes an infinite loop on render

### ISSUE THREAD

**Issue by IceDragon200** [DockYard/elixir-mail#60]
Putting an empty or nil value into a header will cause an infinite loop in the `render_header_value`
Since there isn't a function for handling empty input.

**Version**
Commit 99facb9860aade3245c2a3288819fd81da31d0e7

**Steps to Reproduce**

```elixir
mail =
  Mail.build
  |> Mail.Message.put_header("x-mms-message-id", nil)
  |> Mail.render
```

**Test Case**
What test case? This thing just loops like nobody's business, you figure it out.

**Expected Behaviour**
Doesn't infinitely loop.
Jokes aside, it should either raise an error, or discard the header.

**Actual Behaviour**
It loops.

**Comment by bcardarella** [comment]
I think it should discard the header. Do you want to PR?

**Comment by archSeer** [comment]
We've traced it down to here: https://github.com/DockYard/elixir-mail/blob/99facb9860aade3245c2a3288819fd81da31d0e7/lib/mail/renderers/rfc_2822.ex#L98

Something like this fixed it but it's probably semantically invalid:

```elixir
defp render_header_value(key, []), do: ""
```

**Comment by bcardarella** [comment]
@archSeer I would handle it here: https://github.com/DockYard/elixir-mail/blob/99facb9860aade3245c2a3288819fd81da31d0e7/lib/mail/renderers/rfc_2822.ex#L163

and create a new function signature:

```elixir
defp do_render_headers([{key, value} | headers]),
  do: do_render_headers(headers)
```

**Comment by IceDragon200** [comment]
You'd have to handle cases with blank strings as well, probably.

Else you may end up with:
```
content-type: yadda
x-mms-message-id: 
other-yadda: somestuff
```

**Comment by bcardarella** [comment]
@IceDragon200 I would match on zero or more whitespace strings. So: `"", " ", "       "` would all be caught

**Comment by IceDragon200** [comment]
You also need to capture empty lists

**Comment by bcardarella** [comment]
@IceDragon200 when would empty lists come up?

**Comment by IceDragon200** [comment]
@bcardarella content-type, it shouldn't happen, but it can happen
