### ISSUE TITLE
`email_regex` is invalid

### ISSUE THREAD

**Issue by the-kenny** [DockYard/elixir-mail#80]
## Version
`0.2.0`

## Test Case
The regular expression used to check email is wrong. It won't accept mail addresses with a domain part containing a non-word character.

## Steps to reproduce
`Mail.build() |> Mail.put_to("foo@bar-baz.com") |> Mail.render()`

## Expected Behavior
The `Mail.render` fn should accept all valid email addresses (or at least all valid domain names).

## Actual Behavior
All domains containing a non-word character (`\w`) are rejected.

Note that too strict email address validation is frowned upon. Email addresses are very hard to verify and very hard to get right. See https://haacked.com/archive/2007/08/21/i-knew-how-to-validate-an-email-address-until-i.aspx/ for some inspiration.

In this case, the check is horribly wrong.

**Comment by bcardarella** [comment]
Yeah that's pretty bad our regex didn't catch this. If you need this ASAP you can override the default regex matcher: https://github.com/DockYard/elixir-mail/blob/master/lib/mail/renderers/rfc_2822.ex#L25

I'll look into making this more permissive by default

**Comment by bcardarella** [comment]
Sorry this sat open for so long. I hope the work around worked for you. On my end I got off my lazy butt and implemented a better regex. I would much prefer to use the `General Email Regex` listed here: https://emailregex.com/ but that regex doesn't parse in Elixir. A more simple one from Swift appears to work and solves for your use case.
