### ISSUE TITLE
Parse errors

### ISSUE THREAD

**Issue by cjbottaro** [DockYard/elixir-mail#83]
## Version
0.2.0

## Test Case
```
File.read!("/tmp/815.txt") |> Mail.Parsers.RFC2822.parse
```

## Steps to reproduce
Download examples (there are three) from here:
https://gist.github.com/cjbottaro/62e8a4e037d015c2996259ff56888256

Then run code above.

## Expected Behavior
To not error.

## Actual Behavior
```
** (MatchError) no match of right hand side value: ["by filter0844p1mdw1.sendgrid.net with SMTP id filter0844p1mdw1-23096-5AF1DA68-1E        2018-05-08 17:12:08.410314999 +0000 UTC"]
    (mail) lib/mail/parsers/rfc_2822.ex:165: Mail.Parsers.RFC2822.parse_received_value/1
    (mail) lib/mail/parsers/rfc_2822.ex:107: Mail.Parsers.RFC2822.parse_headers/2
    (mail) lib/mail/parsers/rfc_2822.ex:19: Mail.Parsers.RFC2822.parse/1
```

Thank for the help!

**Comment by bcardarella** [comment]
Can you try master?

**Comment by cjbottaro** [comment]
Master doesn't fix it.

I've come to realize that there is a lot of bad email out there. I downloaded my entire Gmail account and ran this lib against all the messages and there are a decent amount of recurring issues:
* invalid dates
* headers not separated from body with `\r\n`
* structured headers having extra semicolons

I have forked the repo and coded workarounds for all these issues... and fortunately all the tests still pass! I'm going to add more tests and clean things up a bit and submit a PR.

Not sure how you would feel about the parser accepting non-conformant message though.

**Comment by TylerPachal** [comment]
@cjbottaro I have been experiencing the same issues, and am curious what you come up with.  It seems we almost need a new parser, something like `Mail.Parsers.Flexible` or `Mail.Parsers.Liberal` which would do it's best to accept everything (which is my use case).

The sorts of problems I have seen:
- Alternate `from` syntaxes
- Multipart emails where one part only has a body (no headers)
- Multipart emails where one part only has headers (no body)
- Incorrect `content-transfer-encoding` headers

I have been working on a fork off of [this other](https://github.com/kbrw/mailibex) (abandoned?) library, but was hoping to move to Dockyard's offering.

**Comment by bcardarella** [comment]
I've been giving this some thought. The statement:

> there is a lot of bad email out there

is absolutely true. The spec has been just a "suggestion" for so long and the implementations are pretty poor. I would prefer to leave the RFC2822 parser as close to spec as possible. But maybe introduce a RFC2822Permissive that is a bit more lenient on some of these cases as cited above.

There is also a very good chance that I misread the spec at times and didn't implement some of the concerns properly. One that jumps out at me is the `\r\n` as there are very clear differences between carriage returns in Windows land and Unix land: http://www.cs.toronto.edu/~krueger/csc209h/tut/line-endings.html

I'm open to suggestions and would very much like to see example emails that demonstrate the failures so I can better understand the pains. Thanks!

**Comment by cjbottaro** [comment]
Gah, I wrote a reply, but forgot to hit send or something...

Anyway, here's my branch:
https://github.com/cjbottaro/elixir-mail/tree/relaxation

It works around the issues I brought up, but none of the stuff that @TylerPachal brought up.

I've had to put this project down for a bit, but hope to return to it soon.

**Comment by TylerPachal** [comment]
Unfortunately I don't have any full-email examples of these problems anymore, but I could share some of the unit tests I do have.  

For the sake of documentation I ran into a new one last week:

- UTF8 encoded subject was missing space after delimiter

Example:

```
# good
=?utf-8?B?wqMgW0xvY2FsIA==?= probe]

# bad
=?utf-8?B?wqMgW0xvY2FsIA==?=probe]
```

Expected output:

```
£ [Local probe]
```

**Comment by andrewtimberlake** [comment]
@TylerPachal Both values in your Example are valid word-encoded values
```elixir
parse_encoded_word("=?utf-8?B?wqMgW0xvY2FsIA==?= probe]")
#=> £ [Local  probe]
parse_encoded_word("=?utf-8?B?wqMgW0xvY2FsIA==?=probe]")
#=> £ [Local probe]
```
According to the [spec](https://tools.ietf.org/html/rfc2047) as I read it the final `?=` ends the encoding and any space after that is normal text again.
Section 2 defines the encoded word as:
```text
encoded-word = "=?" charset "?" encoding "?" encoded-text "?="
```

NOTE: Word encoding wasn’t supported in this library but I added it about 2 weeks ago in commit 519cc0e

**Comment by andrewtimberlake** [comment]
@cjbottaro I have done a lot of work on getting this library to parse invalid `Received:` headers.
I’m going to close this issue.
If you find any more parse errors in the wild, please open an issue with an example email and I’ll fix the parser accordingly.
